### ISSUE TITLE
Route53: dynamic record triggers update even with no changes to the record

### ISSUE THREAD

**Issue by ttk** [octodns/octodns-route53#10]
I have the following dynamic record:
```
www:
  dynamic:
    pools:
      eu:
        values:
        - value: aloadofELBstuffhere.amazonaws.com.
    rules:
    - geos:
      - EU
      pool: eu
  ttl: 300
  type: CNAME
  value: web.example.com.
```

When I sync to route53, it creates the record(s) the first time. All good. When I run a sync the second time, it reports an update, even though nothing has changed:

```
* route53 (Route53Provider)
*   Update
*     <CnameRecord CNAME 300, www.testing123.com., web.example.com., {'eu': {'fallback': None, 'values': [{'value': 'aloadofELBstuffhere.amazonaws.com.', 'weight': 1}]}}, [{'pool': 'eu', 'geos': ['EU']}]> ->
*     <CnameRecord CNAME 300, www.testing123.com., web.example.com., {'eu': {'fallback': None, 'values': [{'value': 'aloadofELBstuffhere.amazonaws.com.', 'weight': 1}]}}, [{'pool': 'eu', 'geos': ['EU']}]> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=3
```

I expect the sync to detect that nothing has changed and Updates=0.
