### ISSUE TITLE
Updating to 0.0.5 breaks previously existing ALIAS records

### ISSUE THREAD

**Issue by petelah** [octodns/octodns-route53#34]
I had our pipelines pulling the latest version of providers and we had not made any DNS changes since May.

We recently raised some changes and ran the plan to find that showed all of our ALIAS records set for deletion. Even after trying to `octodns-dump` the records they were still skipped: `[4305765760] WARNING YamlProvider[dump] Route53Provider/ALIAS records not supported for cdn.*****.com.; omitting record` 

Where as usually we would get: `[4345644416] WARNING Route53Provider[route53] cdn.****.com. is an Alias record. Skipping...` and the record would be skipped.

I am unsure if I would have to add these records in manually(which we have hundreds and would take a very long time) or I am missing something in config here.

An example of the plan output that occurs to all our ALIAS records when running with `0.0.5`:
```
Delete | ****** | Route53Provider/ALIAS | 942942942 | "******.amazonaws.com." A *****
-- | -- | -- | -- | --
```

I obviously haven't tested if this actually deletes them since I have no intention of deleting them. But also haven't tested this in an isolated environment.

So for now we are pinning to version `0.0.4` which will skip ALIAS records.

**Comment by ross** [comment]
https://github.com/octodns/octodns/pull/924 should get dump supporting 3rd party/dynamically registered types. 

There were oversights/bug(s) in the way of dump support for Route53's alias type. `Provider._processed_desired_zone` was doing its own `type in provider.SUPPORTS` check rather than using `provider.supports(record)`. There are a few providers that already did extra logic in `supports` that `_process_desired_zone` wouldn't utilize. 

Once that was fixed, `YamlProvider` needed to override that method and say that it always supports everything via `return True`. 

If you check out that branch you should be able to get a dump with all of the Alias records included. I'm going to do some manual testing of that to verify as well.

So as for next steps for you there's two possible paths:
1. Assuming this works, dump all the missing records and either replace your configs with the dumps or pull the aliases out into your configs and have them be managed going forward
2. If you'd rather just leave those record unmanaged you should be able to configure a [`TypeRejectlistfilter`](https://github.com/octodns/octodns/blob/master/octodns/processor/filter.py#L31) and tell it to ignore the `Route53Provider/ALIAS` type.


I'm still trying to decide what the best course of action is around the CHANGELOG and version numbering...

**Comment by ross** [comment]
Verified a dump with an `Route53Provider/ALIAS` record configured in the UI worked:

```yaml
alias:
  ttl: 942942942
  type: Route53Provider/ALIAS
  value:
    evaluate-target-health: true
    hosted-zone-id: null
    name: ''
    type: A
```

Route53's ALIAS type doesn't support ttls so that value is a default/sentinal value implemented in the provider. You can omit it and let the default value from the `YamlProvider` take effect. Either way it'll be ignored.

**Comment by ross** [comment]
Example of the ignore if you want to go that route:

```yaml
...
processors:
  ignore-r53-alias:
    class: octodns.processor.filter.TypeRejectlistFilter
    rejectlist:
      - Route53Provider/ALIAS

zones:
  exxampled.com.:
    sources:
      - config
    processors:
      - ignore-r53-alias
    targets:
      - route53
```
