### ISSUE TITLE
Does Octodns-route53 support sub-domain NS records

### ISSUE THREAD

**Issue by rkatragadda-travelbrands** [octodns/octodns-route53#87]
Does OctoDNS supports sub domain NS records?

for example.com i have subdomain email.example.com and config file as below however I can't see it is getting created in Route53 and other records are in place.
under config/example.com.yaml i have like below
where I also have other record type of txt with same name!

```yaml
email:
ttl: 300
type: NS
values:
- a.ns.campaign.adobe.com.
- b.ns.campaign.adobe.com.
- c.ns.campaign.adobe.com.
- d.ns.campaign.adobe.com.
email:
  ttl: 30
  type: TXT
  value: "google.com"
```

Edit: @ross added yaml quotes so that things would ~format

**Comment by rkatragadda-travelbrands** [comment]
if I removed txt type NS records are getting created!

**Comment by ross** [comment]
Multiple records on the same name/node are done as YAML arrays. The above essentially specifies the key `email` twice and afaik spec-wise the last one will win, overwriting the first. It should probably look something like:

```yaml
email:
  - ttl: 300
    type: NS
    values:
      - a.ns.campaign.adobe.com.
      - b.ns.campaign.adobe.com.
      - c.ns.campaign.adobe.com.
      - d.ns.campaign.adobe.com.
  - ttl: 30
    type: TXT
    value: "google.com"
```
